language: python
python:
  - 3.6

before_install:
  - python3 -m pip install coverage
install:
  - python3 -m pip install -r requirements.txt
script:
  - python3 -m coverage run test_encrypt.py
after_success:
  - codecov
